---

- name: "AWS - Install docker"
  hosts: all
  # hosts: jenkins_agents
  
  become: true

  tasks:
    - name : "Create Groups"
      group:
        name: "{{item}}"
        state: "present"
      with_items:
        - sudo

    - name: Add the user 'devops' and add it to 'sudo'
      user:
        name: devops
        create_home: yes 
        state: present 
        generate_ssh_key: true
        ssh_key_file: .ssh/id_rsa 
        ssh_key_type: rsa 

    - name: Add devops user to suduers
      shell: "echo 'devops ALL=(ALL) NOPASSWD: ALL' | tee /etc/sudoers.d/devops"

    - name: Add SSH key to 'devops'
      authorized_key:
        user: devops
        state: present
        key: "{{ lookup('file', pub_key) }}"

    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - java-1.8.0
        - python-pip
        - git

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install alternatives
      shell: alternatives --install /usr/bin/java java /usr/java/latest/bin/java 1

    - name: Install extras epel
      shell: amazon-linux-extras install -y epel

    - name: Install extras docker
      shell: amazon-linux-extras install -y docker

    - name: Install extras docker
      shell: usermod -a -G docker ec2-user

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install aws-cli
      shell: pip install awscli





# sudo yum update -y
# sudo yum install java-1.8.0 -y
#sudo alternatives --install /usr/bin/java java /usr/java/latest/bin/java 1 -y
# sudo amazon-linux-extras install -y docker
# sudo usermod -a -G docker ec2-user
# id ec2-user
# sudo systemctl enable docker.service
# sudo systemctl start docker.service
# sudo systemctl status docker.service
# sudo docker version

# # sudo yum install epel-release -y
# # sudo yum install python-pip -y
# sudo pip install awscli
# sudo yum install git -y