---
# tasks file for common-setup-role
#
- name : "Create Groups"
  group:
    name: "{{item}}"
    state: "present" 
  with_items:
    - sudo

- name: Add the user 'devops' and add it to 'sudo'
  user:
    name: devops
    create_home: yes 
    state: present 
    generate_ssh_key: true
    ssh_key_file: .ssh/id_rsa 
    ssh_key_type: rsa 

- name: Add devops user to suduers
  shell: "echo 'devops ALL=(ALL) NOPASSWD: ALL' | tee /etc/sudoers.d/devops"

- name: Add SSH key to 'devops'
  authorized_key:
    user: devops
    state: present
    key: "{{ lookup('file', pub_key) }}"