---
- name: "EC2 - Register Agent In Master Casc"
  hosts: all
  become: true

  roles:
        - ../roles/agent-auth

  tasks:
    - name: Register agent IP in Jenkins Master casc
      shell:  |
        JenkinsContainerId=$(docker ps --filter="name=jenkins" --format="{{ '{{' }}.ID}}")
        echo "$JenkinsContainerId"
        docker exec -it $JenkinsContainerId cat /var/jenkins_home/casc.yaml
        docker exec -it $JenkinsContainerId sed -i "s/{{ '{{' }}JENKINS_AGENT_URL}}/{{ private_ip }}/" /var/jenkins_home/casc.yaml
        docker exec -it $JenkinsContainerId cat /var/jenkins_home/casc.yaml
            