---
- name: "EC2 - Install Jenkins Agent"
  hosts: all
  # hosts: jenkins_agents
  become: true

  roles:
    - ../roles/common-setup-role # Full path to role
    - ../roles/git # Full path to role
    - ../roles/docker # Full path to role
    - ../roles/ansible

  tasks:
    - name: Install httpd
      shell: yum install -y httpd
    - name: Enable httpd service at startup
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Hello World
      shell: echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html

    #- name: Create NodeExporter directory
      #shell: mkdir -p /home/ec2-user/node_exporter

    - name: Install aws-cli
      shell: pip install awscli

    - name: Expose Dockerhost - replace line in file
      shell: sed -i "/.*ExecStart=.*/c\\ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock" /lib/systemd/system/docker.service

    - name: Reload docker deamon
      shell: systemctl daemon-reload

    - name: sudo service docker restart
      shell: service docker restart

    - name: verify accessibility
      shell: curl http://{{ private_ip }}:4243/version

    - name: verify accessibility - Localhost
      shell: curl http://localhost:4243/version
    
    # - name: Register agent IP in Jenkins Master casc
    #   hosts: {{ JENKINS_MASTER_URL }}
    #   shell:  |
    #     JenkinsContainerId=$(docker ps --filter="name=jenkins" --format="{{ '{{' }}.ID}}")
    #     docker exec -it ${JenkinsContainerId} sed -i "s/{{ '{{' }} JENKINS_AGENT_URL }}/{{ private_ip }}/" /var/jenkins_home/casc.yaml

#        sed -i "s/{{JENKINS_AGENT_URL}}/{{ private_ip }}/" /var/jenkins_home/casc.yaml

# docker ps --filter="name=jenkins" --format="{{.ID}}"

      # Replace {{JENKINS_AGENT_URL}} with {{ private_ip }}  in casc
      #  sed -i "s/{{JENKINS_AGENT_URL}}/0.0.0.0/" /home/casc.yaml
      #  docker exec -it ${JenkinsContainerId} sed -i "s/{{ JENKINS_AGENT_URL }}/{{ private_ip }}/" /home/casc.yaml



# Replace JCASC file in master and reload configuration


# sudo yum update -y
# sudo yum install java-1.8.0 -y
#sudo alternatives --install /usr/bin/java java /usr/java/latest/bin/java 1 -y
# sudo amazon-linux-extras install -y docker
# sudo usermod -a -G docker ec2-user
# id ec2-user
# sudo systemctl enable docker.service
# sudo systemctl start docker.service
# sudo systemctl status docker.service
# sudo docker version

# # sudo yum install epel-release -y
# # sudo yum install python-pip -y
# sudo pip install awscli
# sudo yum install git -y
