---
# tasks file for elk
- name: Increase memory
  shell: "sysctl -w vm.max_map_count=262144"

- name: pull an image
  docker_image:
    name: sebp/elk
    source: pull
    tag: latest

- name: Restart a container
  docker_container:
    name: elk
    image: sebp/elk
    state: started
    restart: yes
    ports:
     - "5601:5601"
     - "9200:9200"
     - "5044:5044"
     - "9300:9300"
     - "9600:9600"



#sysctl -w vm.max_map_count=262144
#docker pull sebp/elk
#docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -p 9300:9300 -p 9600:9600 -it --name elk sebp/elk